workflows:
  android-release:
    name: Android Release
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Flutter doctor
        script: flutter doctor -v
      - name: Pub get
        script: flutter pub get
      - name: Build APK release
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
